from pydantic import BaseModel, Field, BeforeValidator, ConfigDict
from typing import Optional, List, Annotated
from bson import ObjectId
import uuid
from datetime import datetime

# Helper to convert ObjectId to string (used for Mongo _id)
PyObjectId = Annotated[str, BeforeValidator(str)]

# ----------------------------------------------------------------
# Product model (unchanged)
# ----------------------------------------------------------------
class ProductModel(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    routine: str
    slot: int
    type: Optional[str] = ""
    name: str
    desc: Optional[str] = ""
    reminder_time : Optional[str] = None

    model_config = ConfigDict(
        populate_by_name=True,
        arbitrary_types_allowed=True,
        json_schema_extra={
            "example": {
                "routine": "morning",
                "slot": 1,
                "type": "Moisturizer",
                "name": "My Cream",
                "desc": "Apply gently",
            }
        },
    )

# ----------------------------------------------------------------
# ToDo model (unchanged)
# ----------------------------------------------------------------
class ToDoModel(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    uid: Optional[str] = Field(default=None, description="User UID that owns this todo")
    text: str
    checked: bool = False
    date: str  # ISO Date string YYYY-MM-DD

    # model_config = ConfigDict(
    #     populate_by_name=True,
    #     arbitrary_types_allowed=True,
    #     json_schema_extra={
    #         "example": {
    #             "uid": "7953f153-222f-428f-8cd0-5aa8354bedb9",
    #             "text": "Complete Morning Routine",
    #             "checked": False,
    #             "date": "2023-10-27",
    #         }
    #     },
    # )

# ----------------------------------------------------------------
# User models – custom uid (UUID4) separate from Mongo's _id
# ----------------------------------------------------------------
class UserCreate(BaseModel):
    """Payload for registration (no fields needed)."""
    pass

class UserRead(BaseModel):
    """Public representation of a user – contains only uid."""
    uid: str = Field(..., description="Unique user identifier generated by the system")
    created_at: datetime

class UserInDB(UserRead):
    """Internal representation – includes Mongo _id."""
    _id: Optional[PyObjectId] = None
    # No hashed_password stored


class Token(BaseModel):
    access_token: str
    token_type: str = "bearer"
    uid: str = Field(..., description="The same uid returned in UserRead")
    model_config = ConfigDict(populate_by_name=True)

# ----------------------------------------------------------------
# Streak model
# ----------------------------------------------------------------
class StreakRecord(BaseModel):
    id: Optional[PyObjectId] = Field(alias="_id", default=None)
    date: str # YYYY-MM-DD
    completed: bool = False
    
    model_config = ConfigDict(
        populate_by_name=True,
        arbitrary_types_allowed=True,
        json_schema_extra={
            "example": {
                "date": "2023-10-27",
                "completed": True,
            }
        },
    )
